version: '3.7'

services:
  database:
    image: mongo:4.4.15
    container_name: 'MongoDB_Container'
    environment:
      -MONGO_INITDB_ROOT_USERNAME: root
      -MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - database-api
  
  extract:
    build: ./etl
    networks:
      - database-api
    depends_on:
      - database

volumes:
  mongodata:
networks:
  database-api:

